.TH "ImageData" 3 "Tue Jun 11 2013" "Version 1.0" "NostalgiaRoom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ImageData \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <testApp\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBImageData\fP &l, const \fBImageData\fP &m)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBimageScore\fP"
.br
.ti -1c
.RI "int \fBalbumnumber\fP"
.br
.ti -1c
.RI "int \fBimageNumber\fP"
.br
.ti -1c
.RI "ofImage \fBtheloadedimage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file testApp\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool ImageData::operator() (const \fBImageData\fP &l, const \fBImageData\fP &m)\fC [inline]\fP"

.PP
Definition at line 44 of file testApp\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int ImageData::albumnumber"

.PP
Definition at line 35 of file testApp\&.h\&.
.SS "int ImageData::imageNumber"

.PP
Definition at line 36 of file testApp\&.h\&.
.SS "float ImageData::imageScore"

.PP
Definition at line 34 of file testApp\&.h\&.
.SS "ofImage ImageData::theloadedimage"

.PP
Definition at line 39 of file testApp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NostalgiaRoom from the source code\&.
