.TH "/Users/rahulbudhiraja/Work/of_v0073_osx_release/apps/myApps/Nostalgia_Spiral/src/main.cpp" 3 "Tue Jun 11 2013" "Version 1.0" "NostalgiaRoom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/rahulbudhiraja/Work/of_v0073_osx_release/apps/myApps/Nostalgia_Spiral/src/main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'testApp\&.h'\fP
.br
\fC#include 'ofAppGlutWindow\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char *argv[])"

.PP
Definition at line 7 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for NostalgiaRoom from the source code\&.
