.TH "/Users/rahulbudhiraja/Work/of_v0073_osx_release/apps/myApps/Nostalgia_Spiral/src/testApp.h" 3 "Tue Jun 11 2013" "Version 1.0" "NostalgiaRoom" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/rahulbudhiraja/Work/of_v0073_osx_release/apps/myApps/Nostalgia_Spiral/src/testApp.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ofMain\&.h'\fP
.br
\fC#include 'ofxXmlSettings\&.h'\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include 'ofxBlur\&.h'\fP
.br
\fC#include 'ofxOsc\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBImageData\fP"
.br
.ti -1c
.RI "class \fBtestApp\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBUSEWII\fP"
.br
.ti -1c
.RI "#define \fBPORT\fP   9000"
.br
.ti -1c
.RI "#define \fBADJUSTTIMEGAP\fP"
.br
.ti -1c
.RI "#define \fBEfficientReorder\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ADJUSTTIMEGAP"

.PP
Definition at line 19 of file testApp\&.h\&.
.SS "#define EfficientReorder"

.PP
Definition at line 21 of file testApp\&.h\&.
.SS "#define PORT   9000"

.PP
Definition at line 15 of file testApp\&.h\&.
.SS "#define USEWII"

.PP
Definition at line 11 of file testApp\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for NostalgiaRoom from the source code\&.
